### ISSUE TITLE
Could you provide the training sequence numbers of MegaDepth ?

### ISSUE THREAD

**Issue by noone-code** [zju3dv/LoFTR#10]
I find there have 197 sequences in MegaDepth Datasets, from `0000` to `5018`.

Could you provide the sequence numbers you used for training LoFTR ?

Is it same as the [one](https://github.com/magicleap/SuperGluePretrainedNetwork/blob/master/assets/megadepth_train_scenes.txt) used in SuperGlue ?

Thank you so much~ 🙂

**Comment by zehongs** [comment]
Hi, it is not the same as the file you pointed to. We use the split recommended by [DISK](https://arxiv.org/pdf/2006.13566v2.pdf), which also seems to be a recent [recommendation](https://github.com/magicleap/SuperGluePretrainedNetwork/issues/33#issuecomment-689848252) by authors from SuperGlue.

<details>

<summary>train list of megadepth</summary>
0001 0003 0004 0005 0007 0012 0013 0016 0017 0023 0026 0027 0034 0035 0036 0037 0039 0041 0042 0043 0044 0046 0047 0048 0049 0056 0057 0058 0060 0061 0062 0064 0065 0067 0070 0071 0076 0078 0080 0083 0086 0087 0090 0094 0095 0098 0099 0100 0101 0102 0104 0107 0115 0117 0122 0129 0130 0137 0141 0147 0148 0149 0150 0151 0156 0160 0162 0175 0181 0183 0185 0186 0189 0190 0197 0200 0204 0205 0212 0214 0217 0223 0224 0231 0235 0237 0238 0240 0243 0252 0257 0258 0269 0271 0275 0277 0281 0285 0286 0290 0294 0299 0303 0306 0307 0312 0323 0326 0327 0331 0335 0341 0348 0360 0377 0380 0387 0389 0394 0402 0406 0407 0411 0446 0455 0472 0476 0478 0482 0493 0496 0505 0559 0733 0768 1017 3346 5000 5001 5002 5003 5004 5005 5006 5007 5008 5009 5010 5011 5012 5013 5017 5018
</details>
