### ISSUE TITLE
关于ScanNet数据集

### ISSUE THREAD

**Issue by Angelo3357** [zju3dv/LoFTR#100]
请问ScanNet数据集中，pose的作用是什么呢？

**Comment by zehongs** [comment]
看到你的一系列问题，让我觉得这位同学是不是没有三维视觉的基础呀？
我建议你可以先学习一下相关的基础课程然后再来提问，我们比较忙，不太有时间帮助你解决这些问题，抱歉！
这里给你推荐一个课程 First Principles of Computer Vision, from Columbia University， 你可以从Camera Calibration开始学习。 https://www.youtube.com/channel/UCf0WB91t8Ky6AuYcQV0CcLw
