### ISSUE TITLE
memory consumption exceeds 80gb!! 

### ISSUE THREAD

**Issue by sanjaypavo** [zju3dv/LoFTR#102]
I have tried matching 2 (2000*2000) images. It took around 80 gb memory for finding 17k matched keypoints.
Attached the screenshot..
![Screenshot from 2021-11-05 12-38-06](https://user-images.githubusercontent.com/93761297/140475225-b732c58a-1242-4f5c-b706-ef1fed688cde.png)
was that normal?

**Comment by zehongs** [comment]
Unfortunately yes. We suggest using a smaller resolution.

**Comment by sanjaypavo** [comment]
Can you please explain how this much memory is consuming

**Comment by zehongs** [comment]
Hi, I'm sorry that I can't remember the exact reason... 
If you could find the code block that leads to this memory bottleneck, I'll definitely be happy to explain the reason.
And in practice, we find a pair of 1200*1200 image can produce good matches. If you need high-resolution matching, you could also try iteratively zoom-in the images.

**Comment by sanjaypavo** [comment]
I am also facing another issue. Input images more than 2000*2000 pixels cannot be matched and facing the below attached error. Can you please explain the reason?
![Screenshot from 2021-11-05 19-32-34](https://user-images.githubusercontent.com/93761297/140523473-8aa4ed23-2152-475a-8c79-8c73cdc97e08.png)

**Comment by zehongs** [comment]
Hi, are you using the correct input shape? Even a single image should be batched...

**Comment by sanjaypavo** [comment]
Yes. It was correct only
![Screenshot from 2021-11-08 11-19-30](https://user-images.githubusercontent.com/93761297/140691172-b1c7e37e-c80a-4151-863c-14881ccc8ca4.png)

**Comment by zehongs** [comment]
I'm not sure about the problem. 
What's the shape of `feat_c0`? It seems its dimension-3 is 500, which represents an image of a width 4000?

**Comment by sanjaypavo** [comment]
Yeah.I've tried images of size 4000*4000 and it was not matching due to this error. So loftr won't match high resolution images???

![Screenshot from 2021-11-10 11-01-30](https://user-images.githubusercontent.com/93761297/141056201-faddeffc-98db-4b8a-b4d8-39682fcbe1b5.png)
I have also attached the **feat_c0** and **feat_c1** shapes

**Comment by zehongs** [comment]
I'm not sure about the performance for such a big image, since LoFTR was trained on smaller ones.
You can modify the default `max_shape` to (500, 500) for images of (4000, 4000) at https://github.com/zju3dv/LoFTR/blob/94e98b695be18acb43d5d3250f52226a8e36f839/src/loftr/utils/position_encoding.py#L11-L19

**Comment by lea-v** [comment]
Hello, thanks for making this work open!
I've ran into the same issue as described here: on trying to run on big images > 2048*2048 px, I need to change the ` max_shape` param in the `PositionEncodingSine` object. Could you share some more insight regarding what changing this value implies please? 
My main concern is aubout pretrained models: would a trained model be impacted with the change of the encoding shape? Is the encoding integrated to the training process? Would the values outside the trained shape be random?
Thanks in advance for your answers
