### ISSUE TITLE
About indoor training.

### ISSUE THREAD

**Issue by zwyking** [zju3dv/LoFTR#103]
Hi, due to large training data of Scannet, I tried to set the number of image pairs in per-scene, from 200 to 100. Then, I use batchsize of 12  and train it for 30 epochs.  I found that its result is same as the result of using default training data with 10 epochs and 12 batchsize.
Is it normal for the declining training data for each epoch?

**Comment by zehongs** [comment]
Hi, it seems the default setting converges faster. I think a bigger dataset helps a lot. Here, the model can see twice the image pairs.

**Comment by zwyking** [comment]
Ok, thanks for your reply!
