### ISSUE TITLE
ScanNet training data

### ISSUE THREAD

**Issue by francescodisalvo05** [zju3dv/LoFTR#104]
Hello, I was trying to reproduce the training loop with scanner and I downloaded the required data from GDrive but the training data has not the same structure of the test data.

The training data contains all .npz files (I am referring to the file both cfg_1513_-1_0.2_0.8_0.15.tar) whereas the test data have actually 4 subfolders each (color, depth, intrinsic and pose)

Thank you!

**Comment by zehongs** [comment]
Hi, the npz files are only the indices. Please follow https://github.com/zju3dv/LoFTR/blob/master/docs/TRAINING.md#scannet to download the ScanNet dataset.
