### ISSUE TITLE
how to reproduce the results on hpatches dataset

### ISSUE THREAD

**Issue by HuangDihe** [zju3dv/LoFTR#105]
Hi,  thanks for your great work.
I want to reproduce the results on hpatches dataset. I use this [tool box](https://github.com/GrumpyZhou/image-matching-toolbox). 
Could you tell me the hyperparameters of LoFTR on hpatches dataset, such as ransac thr?

**Comment by zehongs** [comment]
Hi, for each pair, we use num_matches≤1024, θc=0.1, ransac_thr=3. Other settings are described as in the paper.

**Comment by Parskatt** [comment]
The toolbox you're using is using pydegensac, which is not the same as opencv:
https://github.com/GrumpyZhou/image-matching-toolbox/blob/83e55bf5ad6a950534aa3c9a89fcbb89a9c7ece8/immatch/utils/hpatches_helper.py#L172
