### ISSUE TITLE
error "conda env create -f environment.yaml "

### ISSUE THREAD

**Issue by shuttworth** [zju3dv/LoFTR#11]
when `conda env create -f environment.yaml `
errors `Solving environment: failed
InvalidVersionSpecError: Invalid version spec: =2.7`

python version:3.8
how to solve this problem?

**Comment by zehongs** [comment]
I can't reproduce the issue. 
It looks like a conda problem, see [link](https://github.com/conda/conda/issues/10618). What version of conda do you use? Have you tried upgrade it to the latest? 
If you can use pytorch in your own environment, I believe it is okay to install requirements via `pip install -r requirements.txt && pip install pytorch_lightning==1.1.8`
