### ISSUE TITLE
data['spv_b_ids'] 是在哪里定义的,代表什么意思？

### ISSUE THREAD

**Issue by ghzhangnj** [zju3dv/LoFTR#110]
Hi，在 https://github.com/zju3dv/LoFTR/blob/master/src/loftr/utils/coarse_matching.py 中 226行中 data['spv_b_ids'] 代表什么意思？ 没有找到关于这个的定义，麻烦指教一下，谢谢！

**Comment by zehongs** [comment]
这个是supervision的batch维度的index。https://github.com/zju3dv/LoFTR/blob/4feac496c1eacebc49ce53793039a8162930935e/src/loftr/utils/supervision.py#L100
