### ISSUE TITLE
A Question about the Image Matching Benchmark 2021 of LoFTR

### ISSUE THREAD

**Issue by Merical** [zju3dv/LoFTR#117]
I’m really impressed by your work LoFTR for correspondence estimation. I noticed that LoFTR showed remarkable performance on the IMC2021. 
I’m wondering how you provide the per-frame keypoints and descriptors for the multiview task (COLMAP)?  I’m working on a custom estimator as well and I hope you may help to answer this question. I managed to extract pairwise key points for the stereo task following the example code on github.com/imc2021-sample-kornia-submission, but the multiview evaluation is still a problem for me.
Looking forward to your response!
Thank you!

**Comment by zehongs** [comment]
Hi, the detector-free method is more suited in the stereo track. And some modifications are needed to adapt it to the multi-view track.
Please refer to out IMC report at https://zju3dv.github.io/loftr/files/LoFTR_IMC21.pdf .

**Comment by Merical** [comment]
Thank you for your response!
I wonder if it's possible for you to provide the LoFTR-SSP code or the results on the IMC2021 validation set? I'm trying to reproduce some experimental results on Phototourism&PragueParks.

**Comment by zehongs** [comment]
I'm sorry that we don't have plans of releasing the code currently...

**Comment by Merical** [comment]
> I'm sorry that we don't have plans of releasing the code currently...

Oh. I understand. Still thanks again!
