### ISSUE TITLE
Hi, how to train the data collected from realsense D435 camera

### ISSUE THREAD

**Issue by ClaudiaShu** [zju3dv/LoFTR#122]
Hi, thanks for your work
I want to train the network with the realsense D435 camera. The data we get from the camera is RGB pictures and depth images. How should we process the data and feed it into the network?
Any suggested process or toolbox?
Many thanks

**Comment by zehongs** [comment]
Hi, the [scannet dataset file](https://github.com/zju3dv/LoFTR/blob/master/src/datasets/scannet.py) might be a good reference. Good luck.
