### ISSUE TITLE
a question on coarse macth

### ISSUE THREAD

**Issue by ghzhangnj** [zju3dv/LoFTR#127]
在coarse_matching.py 文件中的 get_coarse_match 函数中 使用了 torch.randint ，会导致重复采样吧？不知道重复采样是否有影响

**Comment by zehongs** [comment]
这个只在训练的时候用，我们没有观察到问题～

**Comment by chemafacil** [comment]
I agree that it can lead to oversampling. Since it happens randomly I guess it does not have big effects but it would probably make sense to change it. 

I think randperm would work to make sure that there is not repeated elements.
```python
# pred_indices is to select from prediction
if num_matches_pred <= num_matches_train - self.train_pad_num_gt_min:
    pred_indices = torch.arange(num_matches_pred, device=_device)
else:
    pred_indices = torch.randperm(
                    num_matches_pred,
                    device=_device)[:num_matches_train - self.train_pad_num_gt_min]
```
