### ISSUE TITLE
I would like to ask whether the path of default.py in the config file needs to be changed after the address is correctly placed. I don't know which ones to modify, but I can't read them now either

### ISSUE THREAD

**Issue by zhubingerdai** [zju3dv/LoFTR#128]
I would like to ask whether the path of default.py in the config file needs to be changed after the address is correctly placed. I don't know which ones to modify, but I can't read them now either

_Originally posted by @zhubingerdai in https://github.com/zju3dv/LoFTR/discussions/124#discussioncomment-1855853_

**Comment by zehongs** [comment]
We overwrite the default configuration. Please create a new one, or modify the configs in `configs` folder.

**Comment by zhubingerdai** [comment]
I asked a question on the '.client ', worried that you could not see it, but this question caused great trouble during my training.

hi，error：can't read data（inflate（） failed）
I only used megadepth to train, but the 'depth' in 'dataset. Py 'gave an error, which seems to be related to '.client'. I only downloaded megadepth dataset for training, do I need to change dataset. Py? Or where?
Looking forward to reply!








Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhubingerdai** [comment]
hi，scripts/reproduce_train/indoor_ds.sh   error：RuntimeError: The given group does not exist




How to fix this error？





Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
