### ISSUE TITLE
Training image size

### ISSUE THREAD

**Issue by adizhol** [zju3dv/LoFTR#13]
Hello,
What image size you used for training? It is unclear from your paper.

Thank you

**Comment by zehongs** [comment]
As stated in section 4.2: 
1. for MegaDepth, images are resized such that their longer dimensions are equal to 840 for training and 1200 for validation 
2. for ScanNet, all images and depth maps are resized to 640 × 480. 

In practice, 1080Ti is able to hold one training batch of 640x640 pair, V100 is able to hold pair larger than 840x840.
