### ISSUE TITLE
Google colab: google drive link for indoor-ds gives 404

### ISSUE THREAD

**Issue by qwertyforce** [zju3dv/LoFTR#130]
Solution:

instead of 
```python
!gdown --id 1w1Qhea3WLRMS81Vod_k5rxS_GNRgIi-O  # indoor-ds
```

```python
!gdown --id 19s3QvcCWQ6g-N1PrYlDCg-2mOJZ3kkgS  # indoor-ds
```
(new weights from https://drive.google.com/drive/folders/1xu2Pq6mZT5hmFgiYMBT9Zt8h1yO-3SIp)

instead of 
```python
if image_type == 'indoor':
  matcher.load_state_dict(torch.load("weights/indoor_ds.ckpt")['state_dict'])
```
```python
if image_type == 'indoor':
  matcher.load_state_dict(torch.load("weights/indoor_ds_new.ckpt")['state_dict'])
```
indoor_ds_new gives 0 matches for 
```python
img0_pth = "assets/scannet_sample_images/scene0711_00_frame-001680.jpg"
img1_pth = "assets/scannet_sample_images/scene0711_00_frame-001995.jpg"
```
idk if it's an intended behavior

**Comment by Wenchao-Gao** [comment]
I met the same problem as you when I use the indoor one. There is 0 matches for it. I wonder if we can use indoor image_type now in Google  colab.

**Comment by zehongs** [comment]
Hi, @qwertyforce , many thanks for pointing out!  
To use the `indoor_ds_new` weights, the config should also be changed.
```python
image_type = 'indoor'
indoor_ds_new_cfg = default_cfg
indoor_ds_new_cfg['coarse']['temp_bug_fix'] = True
matcher = LoFTR(config=indoor_ds_new_cfg)
```

**Comment by DavidTu21** [comment]
Hi @zehongs , thanks for the updated usage, may I ask should I change this config in the file demo_loftr.py or any other files? Thank you in advance for your time and help.

**Comment by tan-tao11** [comment]
> Hi, @qwertyforce , many thanks for pointing out! To use the `indoor_ds_new` weights, the config should also be changed.
> 
> ```python
> image_type = 'indoor'
> indoor_ds_new_cfg = default_cfg
> indoor_ds_new_cfg['coarse']['temp_bug_fix'] = True
> matcher = LoFTR(config=indoor_ds_new_cfg)
> ```

The problem still exists after changing the config in the corresponding code cell.
