### ISSUE TITLE
A possible minor bug in logging

### ISSUE THREAD

**Issue by vdvchen** [zju3dv/LoFTR#131]
Hi,

Thanks for your great work! I'm reading your code for logging and find there might be some minor bugs.

In [this line](https://github.com/zju3dv/LoFTR/blob/94e98b695be18acb43d5d3250f52226a8e36f839/src/utils/plotting.py#L132), it seems that all matches in a batch are intented to be logged, since there's a loop over the batch. However, the append operation is out of the loop which makes only the final instance be logged.

**Comment by zehongs** [comment]
Hi!
Thanks for pointing out, we've fixed this in commit [2122156](https://github.com/zju3dv/LoFTR/commit/2122156015b61fbb650e28b58a958e4d632b1058).
