### ISSUE TITLE
spv_b_ids issues

### ISSUE THREAD

**Issue by Hoyeon-Ahn** [zju3dv/LoFTR#135]
Hello!

First of all, thank you for your great works!

I try to run your code (notebook/demo_single_pair.ipynb) with a pretrained model what you give 'indoor_ds_new.ckpt'.

but I had a simple problem on this parts.

utils\coarse_mathcing.py <-

The error message said, 'KeyError: spv_b_ids'  

How can I fix it? I saw data but there is no dictionary key called 'spv_b_ids'

Thanks in advance!

**Comment by zehongs** [comment]
Hi, the prefix `spv` stands for supervision. Please make sure you're using the `eval()` mode?
