### ISSUE TITLE
Would you mind referring to QuadTree attention?

### ISSUE THREAD

**Issue by Tangshitao** [zju3dv/LoFTR#147]
Hi, I am the author of 'QuadTree Attention for Vision Transformers', https://arxiv.org/abs/2201.02767. Based on LoFTR, QuadTree attention is able to improve the performance to 61.8 for AUC@20. We have released our codes in https://github.com/Tangshitao/QuadTreeAttention. I would appreciated if you can refer to our work.

**Comment by Qing-WANG-KIT** [comment]
Are the computational costs of QuadTree Attention and Linear Attention similar?

**Comment by zehongs** [comment]
I'm closing this issue since the QuadTreeAttention is referred in the readme.
