### ISSUE TITLE
code issues

### ISSUE THREAD

**Issue by geovsion** [zju3dv/LoFTR#148]
您好，我发现您coarse matching label制作中似乎用到了深度一致性检验；并且论文中写到的使用grid的中心来寻找互最近邻，这好像与代码有些不符。我还有个问题是，深度图如果扩展至2000*2000，在采样的时候不会导致采样深度不符合原图的问题吗？

**Comment by zehongs** [comment]
在代码里面，我们没有实际使用检验得到的mask。而是用了所有变换后的结果去计算mnn。
拓展至2000*2000是为了组batch。不会导致采样失败，因为我们妥善处理了图像的缩放问题。
