### ISSUE TITLE
Question About Results of Superglue on MegaDepth Dataset

### ISSUE THREAD

**Issue by HuangDihe** [zju3dv/LoFTR#149]
Hello, I would like to ask if the metrics of superglue on the megadepth dataset in the paper use the official model or the model you retrained. The metrics I get using the official superglue model are lower than the metrics of superglue in your paper, can you please tell me what are the hyperparameters and what are the hyperparameters of ransac when you use superglue?
Thanks!

**Comment by zehongs** [comment]
Hi, we use the official setting and weights from the SuperGlue repository. Ransac error threshold is set as 1.0, the confidence is set as 0.99999.

**Comment by HuangDihe** [comment]
> Hi, we use the official setting and weights from the SuperGlue repository. Ransac error threshold is set as 1.0, the confidence is set as 0.99999.

Thanks. Does superpoint have the following hyperparameters: maximum image edge equal to 1200, maximum number of keypoints equal to 2048 and nms radius equal to 3 ?

**Comment by zehongs** [comment]
Hi, as the test-config suggests,  we detect 2048 keypoints, the nms radius is set as 4, the maximum image edge is set to 1600

**Comment by HuangDihe** [comment]
> Hi, as the test-config suggests, we detect 2048 keypoints, the nms radius is set as 4, the maximum image edge is set to 1600

Thanks !
