### ISSUE TITLE
Details of reproducing InLoc localisation

### ISSUE THREAD

**Issue by vdvchen** [zju3dv/LoFTR#150]
Hi, thanks for your great works.

I'm trying to reproduce your results on InLoc localisation. As is suggested in paper, LoFTR is combined with HLoc to perform visual localisation. I integrate LoFTR into the  inloc pipeline and find some performance gap compared with the reported in paper.  
Would you mind sharing some experiment details on InLoc reproduction, that should be very helpful!

I understand some settings are elaborated on the leaderboard(https://www.visuallocalization.net/details/19843/), like using _pairs-query-netvlad40-temporal.txt_ as retrieval list and using outdoor model(please correct me if I'm wrong). But some other details like resize and threshold should also matter.

Thanks!

**Comment by zehongs** [comment]
Hi,  I think the major difference is that we used the finetuned version of the outdoor-OT model, the skh-iter is set as 3 and the confidence threshold is set as 0.2. 
The augmentation is as follows.
https://github.com/zju3dv/LoFTR/blob/2122156015b61fbb650e28b58a958e4d632b1058/src/utils/augment.py#L4-L19

**Comment by vdvchen** [comment]
Thanks for your help!
