### ISSUE TITLE
粗匹配直接预测特征点坐标

### ISSUE THREAD

**Issue by yeyang16** [zju3dv/LoFTR#152]
感谢您们卓越的工作，我有个疑问：粗匹配那一步相当于将图像切patch，特征点可以看做是patch的中心点即棋盘格点，transformer时直接预测坐标点可行吗，即在第一步transfomer后对所得到的的特征向量（N dim）——》（N 2）（即N对变换前后坐标，且一一对应可直接算出单应矩阵）

**Comment by Xylon-Sean** [comment]
@yeyang16 这个 idea 咋和这篇有点像

https://github.com/ubc-vision/COTR

**Comment by yeyang16** [comment]
@Xylon-Sean 谢谢您! 居然已经有这样的工作了，感谢

**Comment by Xylon-Sean** [comment]
@yeyang16 没事没事 😊
