### ISSUE TITLE
MegaDepth scene_info where is pair_info?

### ISSUE THREAD

**Issue by MACILLAS** [zju3dv/LoFTR#155]
Hi authors, 

I've really enjoyed reading about your method and I think it would be especially useful in civil inspection tasks (i.e., low feature environments). I'm trying to finetune your pretrained model with some data that we have collected.

So in the MegaDepth index you provided for example ./scene_info_0.1_0.7/0000_0.1_0.3.npz there is image_paths, depth_paths, intrinsics, poses and pair_info. 

However, in d2-net's scene_info folder we have 0000.0.npz and there isn't a field called pair_info.
The code below is from d2-net/megadepth_utils/preprocess_scene.py line 230-241. 

np.savez(
    os.path.join(args.output_path, '%s.npz' % scene_id),
    image_paths=image_paths,
    depth_paths=depth_paths,
    intrinsics=intrinsics,
    poses=poses,
    overlap_matrix=overlap_matrix,
    scale_ratio_matrix=scale_ratio_matrix,
    angles=angles,
    n_points3D=n_points3D,
    points3D_id_to_2D=points3D_id_to_2D,
    points3D_id_to_ndepth=points3D_id_to_ndepth
)

Can you help me understand what happened between these two?

Many Thanks, 

Max

**Comment by zehongs** [comment]
Hi Max,
The D2Net npz gives you information for each image. 
We need to use some criteria to pick specific pairs for training.
Please check out this issue.
https://github.com/zju3dv/LoFTR/issues/85

**Comment by MACILLAS** [comment]
Thank you :)
