### ISSUE TITLE
For MegaDepth,What image size you used for training?

### ISSUE THREAD

**Issue by Naysanado** [zju3dv/LoFTR#157]
Hello:
I don't understand here: for MegaDepth, images are resized such that their longer dimensions are equal to 840 for training and 1200 for validation

You mean that for training the size are resized 840 X 840，for validation the size are resized 1200 X 200?

**Comment by zehongs** [comment]
Hi,
We don't change the aspect ratio. But the input image tensor is in square shape, which is achieved by zero padding.

**Comment by Naysanado** [comment]
感谢您的回复！
1：我理解您的意思了 您的意思指的是如果图片为30 X 40  那么通过0填充   训练集改为 630   X 840   验证集改为 900 X 1200?

2:   在demo_single_pair.ipnd中  对于室外的模型权重   图片resize的大小是不是8的倍数就可以了呢  我试了下将图片resize到640 X 192依旧可以检测匹配对。

3：我如何指定尺寸为640 X 192去训练MegaDepth呢

**Comment by zehongs** [comment]
1. 我不太确定你说的意思，不过你可以通过确认dataset文件夹下面的代码核查具体的行为。
2. 是，8的倍数就可以。
3. 修改config文件。

**Comment by Naysanado** [comment]
感谢您的回复！
您好 我看了下代码 发现是使用了更小的尺寸640 X 640去训练outdoor场景 我目前的理解是：您可能是为了让input image尺寸为正方形 然后您选择了较长的边长，比如一张640 X 320的图片 我想问下您是通过0填充将图片resize到640 X 640去训练的吗

**Comment by zehongs** [comment]
对
