### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by zhirui-gao** [zju3dv/LoFTR#158]
RuntimeError: CUDA out of memory. Tried to allocate 358.00 MiB (GPU 0; 11.77 GiB total capacity; 5.35 GiB already allocated; 232.31 MiB free; 6.41 GiB reserved in total by PyTorch) my GPU is 3080Ti
I have set the batch_size to be 1,It is normal?

**Comment by zehongs** [comment]
Yes.
Try to make your input image pair smaller.

**Comment by zhirui-gao** [comment]
Thanks for you reply
