### ISSUE TITLE
Could you provide the Scannet training pairs? 

### ISSUE THREAD

**Issue by lijiaman** [zju3dv/LoFTR#16]
Hi there,

Could you please help provide the training pairs for Scannet (maybe just a txt file)?  It seems generating the pairs need quite long time, that would be really helpful if you already have that. Thanks a lot！

**Comment by zehongs** [comment]
Hi, the ScanNet metadata (~21G) is on the server of the company. I think we can handle this after the labour day holiday. And I personally recommend you using the MegaDepth dataset, which offers better depth quality and requires much less training time.

Just notice: we plan to release the whole training code/data around 2021-6-10.

**Comment by lijiaman** [comment]
Hi zehong,

Thanks for the quick reply. We also use megadepth, but it would be better
to use scannet as well for comparison with previous work. Really appreciate
it if you could share the pairs of scannet data! Happy holidays! Thank you!

**Comment by JiamingSuen** [comment]
We've added the training pair info on ScanNet to the [README](https://github.com/zju3dv/LoFTR#image-pair-info-for-training-on-scannet). Feel free to reopen this issue if you met any problems.
