### ISSUE TITLE
The network visualize

### ISSUE THREAD

**Issue by zhirui-gao** [zju3dv/LoFTR#162]
Have you tried to use _self.logger.experiment.add_graph_ to visualize the network structure ？
When I try to use it in _train.py_,there is a error that i can't solve?
**My code**
```
img0 = torch.rand((1, 1, 480, 640)).cuda()
img1 = torch.rand((1, 1, 480, 640)).cuda()
batch_test = {'image0': img0, 'image1': img1,}
logger.experiment.add_graph(model, batch_test)
```
**Error**
```
line 201, in _forward_unimplemented
    raise NotImplementedError
NotImplementedError
```

**Comment by zehongs** [comment]
Hi, I think this is related to tensorboard.
