### ISSUE TITLE
Questions about the dropout setting

### ISSUE THREAD

**Issue by colorfulgreen** [zju3dv/LoFTR#163]
Hi, many thanks for your nice job! 

I'm trying to follow your work in stereo matching, and have some questions about the ``dropout`` setting in training details. In my experiments,  ``dropout=0.`` promotes convergence on simple networks, but hinders convergence on more complex networks.

In the [supplementary material](https://zju3dv.github.io/loftr/files/LoFTR-suppmat.pdf) of LoFTR, it mentions that  

    We don’t use dropout for regularization as usually used when training Transformers.

Is this out of any consideration?

**Comment by zehongs** [comment]
We did some experiments with dropout>0, and the results were similar to dropout=0.

**Comment by colorfulgreen** [comment]
Okay, got it, thanks for the information!
