### ISSUE TITLE
Question about Position Encoding

### ISSUE THREAD

**Issue by HanzhiC** [zju3dv/LoFTR#17]
https://github.com/zju3dv/LoFTR/blob/a0cf1fcebb0ed06d7ce8689bf3d8325a4a7668ca/src/loftr/utils/position_encoding.py#L21

Hi, thanks very much for your great work!

While I am confused about how you formulate the position encoding here, looks that it is different how you definite in your paper. Could you please elaborate more on that?

I thought it would more like the following according to your pape?

       `div_term = (1/10000.0) ** (torch.arange(0, d_model//2, 2).float()/ d_model )`

Thanks!

**Comment by zehongs** [comment]
I’m very sorry for the earlier reply😅. They are actually the same. This is an implementation trick of exp(log()), which is to prevent computing the exponential of a large base number, i.e. 10000.
