### ISSUE TITLE
What is the configuration of the four 44m pre-training models you gave.

### ISSUE THREAD

**Issue by FujiwaraZayako** [zju3dv/LoFTR#172]
My current configuration is 640size, and everything else is the default. The trained CKPT size reached 132.52m. Why
![uTools_1650439842084](https://user-images.githubusercontent.com/73938267/164174624-09440a08-b255-419c-b5e6-63b980cd8eff.png)
?

**Comment by miRemid** [comment]
did you solve this problem? my ckpt size also reached 133m, but i dont't know why

**Comment by zehongs** [comment]
please remove the optimizer parameters in the ckpt.

**Comment by miRemid** [comment]
works, thank you👍
