### ISSUE TITLE
About cross attention

### ISSUE THREAD

**Issue by ohkwon718** [zju3dv/LoFTR#176]
Hi, thanks for sharing your amazing work. The paper is really amazing.
I have a question about the implementation for cross attention.
https://github.com/zju3dv/LoFTR/blob/2122156015b61fbb650e28b58a958e4d632b1058/src/loftr/loftr_module/transformer.py#L95-L97

As far as I understood, the input pairs of each cross attention are the same but only switched. But in the code, the result of the first cross attention is re-fed to the second attention. 
Isn't it a mistake or did you actually intend it to work like that?

**Comment by zehongs** [comment]
Hi, this is a "mistake". We experimented a bit with it and found that it performed better than the "correct" way.

**Comment by ohkwon718** [comment]
Thanks for the reply.
Was it significantly better or just a little number of improvements?
Because I am trying to adopt your transformer into my code and it gets my training broken for some reason.
So, if there is no significant difference in your case, I would choose the correct way.

**Comment by zehongs** [comment]
Hi,
LoFTR-DS AUC@10 on Scannet: 40.8 v.s. 40.1. I think you can correct this "buggy" implementation.

**Comment by ohkwon718** [comment]
Thank you very much!
