### ISSUE TITLE
Questions about names of variables

### ISSUE THREAD

**Issue by park-youngjae** [zju3dv/LoFTR#18]
Thank you for your wonderful work.
I have questions about your code variables.

At LoFTR/src/loftr/utils/coarse_matching.py,
Can you tell me what each "coarse_matches" id means?
(b_ids, i_ids, j_ids, gt_mask, m_bids, mkpts0_c, mkpts1_c, mconf)

Thank you!

**Comment by JiamingSuen** [comment]
`b_ids`: batch indices
`i_ids`: indices of the selected coarse matches on image 0
`j_ids`: indices of the selected coarse matches on image 1
`gt_mask`: this variable is only used during training. In the training code, gt matches will be padded to the selected matches to ensure the same batch size among image pairs.
`mkpts0_c`: matched keypoints at the coarse level on image 0
`mkpts1_c`: matched keypoints at the coarse level on image 1
`mconf`: the matching confidence

**Comment by park-youngjae** [comment]
Thank you for your quick response!
