### ISSUE TITLE
D2-Net preprocessed images 404 error

### ISSUE THREAD

**Issue by sanssouci7** [zju3dv/LoFTR#208]
Hi,I tried to download  [D2-Net preprocessed images](https://drive.google.com/drive/folders/1hxpOsqOZefdrba_BqnW490XpNX_LgXPB)  in training.md ,but it occurs 404 error ,could you add an available link

**Comment by curious-energy** [comment]
Yes, the same problem occurs, could a contributor help or make a suggestion?

**Comment by zehongs** [comment]
I'm not sure about the license. Please do as the author of D2Net said in the issue https://github.com/mihaidusmanu/d2-net/issues/93#issuecomment-1211805143
.

**Comment by ewrfcas** [comment]
As discussed in this issue (https://github.com/mihaidusmanu/d2-net/issues/26#issuecomment-543748938), there are negligible differences between Megadepth images and D2-Net images. If we use the intrinsic and extrinsic provided in 'train-data/megadepth-indices', can we directly use images from Megadepth_v1 (199GB)?

**Comment by QiuhangLiu** [comment]
> 

Hi mate! May I ask that did you figure out what are these data means? (undistorted images, intrinsic, extrinsic, with distorted Megadepth depth) I am really confused because for megadepth, I only download that 199GBdata and the indices provided by LoFTR. But the training got error.
