### ISSUE TITLE
最近邻准则的具体流程是什么

### ISSUE THREAD

**Issue by pisces365** [zju3dv/LoFTR#212]
请问粗匹配过程中最近邻准则的具体流程是怎么样的，看代码没看明白

**Comment by zehongs** [comment]
用一个mask记录符合的匹配点。需要是大于conf，互相都是最近邻。代码中第3步是为了节省显存。训练时会pad一些gt的pair。最后一步是换算到fine-level的id（和coarse-level总的pixel数量不一样，因此id也不一样）
