### ISSUE TITLE
Robustness against rotation and flipping

### ISSUE THREAD

**Issue by repoit** [zju3dv/LoFTR#213]
For my use case, images might be flipped or rotated. However, the model doesn't perform well on these images (see the example below). Do you believe the model would get robust against these transformations if I added augmentation for rotation and flipping during the training process?

![ex2](https://user-images.githubusercontent.com/99652776/187851184-76ebd19c-9f27-46c1-b38d-c9af98ee0797.png)
*Two images showing the same scene with high matching rates*

![ex1](https://user-images.githubusercontent.com/99652776/187851194-b027b066-e7ff-40f0-b662-58137f8800ce.png)
*When flipped, no good matches are detected*

**Comment by Varun-Tandon14** [comment]
@repoit you might want to try [SE2-LoFTR](https://arxiv.org/abs/2204.10144) ([official repo](https://github.com/georg-bn/se2-loftr)). From my limited experience, SE2-LoFTR seemed to perform reasonably well for rotations of 30 degrees.  Hopefully, this helps.

**Comment by zehongs** [comment]
Augmentation will be helpful.
I believe SE2-LoFTER can also handle this problem to a certain extent.
Another useful trick is to run LoFTR multiple times, e.g. [{image0, image1}, {rot90-image0, image1}, {rot180-image0, image1}, {rot270-image0, image1}, {flipped-images0, image1}] and take the union of all derived matches . While this can be batched, it can require a lot of GPU memory and a longer time😂

**Comment by repoit** [comment]
> Augmentation will be helpful.

Great. I will then setup the training pipeline using MegaDepth and augment the existing training data with rotated/flipped cases. Is there anything important I should consider before doing so, or is it sufficient to just augment the data and follow [your instructions for training](https://github.com/zju3dv/LoFTR/blob/master/docs/TRAINING.md)?

> Another useful trick is to run LoFTR multiple times, e.g. [{image0, image1}, {rot90-image0, image1}, {rot180-image0, image1}, {rot270-image0, image1}, {flipped-images0, image1}] and take the union of all derived matches . While this can be batched, it can require a lot of GPU memory and a longer time😂

I like this approach, but efficiency is key in our application.

> SE2-LoFTER

The SE2 model does indeed work better (see example below). I believe it's interesting to compare the results using SE2 to LoFTR when trained with augmented data.

![se2_example](https://user-images.githubusercontent.com/99652776/187889115-7dee1956-97c6-461a-af86-82f59ae80c88.png)

*Comparison of SE2 non-flipped (left) and flipped (right) when using the 8rot.ckpt model weights*

**Comment by zehongs** [comment]
Training LoFTR requires lots of GPUs. And augmentation is likely to hurt the performance of matching "normal" image pairs.

**Comment by r-silva-acsl** [comment]
@repoit Did you or anyone finally apply data augmentation?  It seems it is necessary to change the `spvs_coarse` function in supervision.py to be able to change the ground truth depending on the rotation applied. Am I right?
