### ISSUE TITLE
Can we direclty use images from Megadepth?

### ISSUE THREAD

**Issue by ewrfcas** [zju3dv/LoFTR#214]
As discussed in this issue (https://github.com/mihaidusmanu/d2-net/issues/26#issuecomment-543748938), there are negligible differences between Megadepth images and D2-Net images. If we use the intrinsic and extrinsic provided in 'train-data/megadepth-indices', can we directly use images from Megadepth_v1 (199GB)?

**Comment by zehongs** [comment]
Hi, intuitively, once you can establish good gt-correspondence for network training, I think the results won't change too much.
