### ISSUE TITLE
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' 

### ISSUE THREAD

**Issue by 123-cq** [zju3dv/LoFTR#216]
想请问一下作者，代码中的torchmetrics对应的版本是多少呀？代码中的environment.yaml没有对应的版本号，同时，该文件中的链接也无法打开。

**Comment by zehongs** [comment]
我们没有用这个包，repo里面搜不到代码

**Comment by zehongs** [comment]
我重新安装了环境。发现是因为版本冲突导致了bug。可以参考
 https://github.com/NVIDIA/DeepLearningExamples/issues/1113#issuecomment-1102969461

https://github.com/zju3dv/LoFTR/blob/8d016feaeb2f8dcc5bf34fd3c675161067299378/requirements.txt#L16
