### ISSUE TITLE
Grocery detection

### ISSUE THREAD

**Issue by Grungeby52** [zju3dv/LoFTR#22]
Hello,
I wonder something, 
https://ai.googleblog.com/2020/07/on-device-supermarket-product.html

 this article has OCR used for product recognition, I think your method could be more efficient. but I'm not sure. your opinion is very important to me. 
In your opinion, which one would be more efficient in recognizing the grocery's product. OCR or Your method?

Best Regards

Onur Güzeldemirci

**Comment by JiamingSuen** [comment]
Hello Onur,

Thanks for your interest in our work. I believe the method mentioned I the article (ROI embedding + OCR) will be 1) faster and 2) more reliable than feature-matching-based methods like LoFTR, mostly because LoFTR is not designed for this task.
