### ISSUE TITLE
match threshold

### ISSUE THREAD

**Issue by Lucifer1002** [zju3dv/LoFTR#220]
Regarding Loftr, how to adjust the matching threshold when running the pre-trained model

**Comment by zehongs** [comment]
Change `config.LOFTR.MATCH_COARSE.THR` before initialize the LoFTR instance.
After matching, you can also find a `mconf` in the updated batch.

**Comment by r-silva-acsl** [comment]
Is there a way to make this Thr a learnable parameter ?
