### ISSUE TITLE
why need add mask_border for mask?

### ISSUE THREAD

**Issue by wangxiaochun520** [zju3dv/LoFTR#221]
how amazing work! when read code，find some confusion about mask_border,
code:
if 'mask0' not in data:
           mask_border(mask, self.border_rm, False)

why need add mask_border for mask? Is it going to be cut off later，border_rm?

**Comment by wangxiaochun520** [comment]
else Is it that the features on the border are not taken into account？

**Comment by zehongs** [comment]
The CNN backbone features on the border is not good, which is due to the zero padding of convolution.

**Comment by wangxiaochun520** [comment]
Thank you。













At 2022-10-21 10:16:33, "Zehong" ***@***.***> wrote:

The CNN backbone features on the border is not good, which is due to the zero padding of convolution.
