### ISSUE TITLE
Question about the training scheduler of ScanNet

### ISSUE THREAD

**Issue by ewrfcas** [zju3dv/LoFTR#223]
Hi, thanks for this great work.

I have a question about training on the full scannet. From the indices provided by the author, there are 428,206,514 (about 0.4 billion) training pairs at all. It will cost a lot of time to train even one epoch. But the training config still uses max_epochs=30 and lr_decay:[3, 6, 9, 12, 17, 20, 23, 26, 29]. Is it reasonable to use an epoch-wise scheduler in such large data?

**Comment by ewrfcas** [comment]
In the paper, the author said that their model could converge in 24 hours of training. How many epochs are used during the training?

**Comment by zehongs** [comment]
Hi,
Is it reasonable to use an epoch-wise scheduler in such large data? 
I'm not sure if it is the best way. But such a scheduler works just fine, probably because of the large batchsize (64) or a specially tailored network design.

How many epochs are used during the training? 
30

**Comment by ewrfcas** [comment]
Thanks for your response!

Do you mean that 30 epochs (12 billion) only cost 24 hours with 64 1080 GPUs? Or just training with a few epochs is enough for the convergence?

Thanks again!

**Comment by ewrfcas** [comment]
Thanks I have understood the mechanism in the class RandomConcatSampler.
