### ISSUE TITLE
Question about the learning rate of 6e-3

### ISSUE THREAD

**Issue by ewrfcas** [zju3dv/LoFTR#225]
Hi, I am confused about the learning rate in default.py.
TRAINER.CANONICAL_BS = 64
TRAINER.CANONICAL_LR = 6e-3

If I run this code with batch=64, it will use lr=6e-3, which is different from "1e-3" as mentioned in the paper.

**Comment by zehongs** [comment]
Hi, sorry for the number inconsistency. 
We've checked the original script, the canonical_bs@lr is 64@6e-3 for the indoor model, 16@2e-3 for the outdoor model.

**Comment by ewrfcas** [comment]
Thanks for your response!
