### ISSUE TITLE
questions on query point refinement.

### ISSUE THREAD

**Issue by minooisbusy** [zju3dv/LoFTR#236]
hello, first of all i appreciate your amazing works. Thank you.

The feature point to be refined in the paper and code is fixed to the point in image B. feature point in image A does not require refinement at the sub-pixel level?

I know that even with SIFT, the coordinates of feature points at the subpixel level are extracted from both images, but if the query point was intentionally made with pixel unit coordinates, I wonder why the algorithm was configured that way.

have a good day. Thanks for reading.

**Comment by zehongs** [comment]
Hi,
Yes, only the points on image B are refined to sub-pixel. The points on image A are at 1/8 grid.
This configuration has been very robust in our experiments, so we did not experiment with adjusting points on image A.
