### ISSUE TITLE
尊敬的作者，想请教一下loftr训练是不是必须有深度图信息

### ISSUE THREAD

**Issue by xuechunliang1** [zju3dv/LoFTR#238]
尊敬的作者，您好。想请教一下如果我只有RGB图像，无法获得深度图信息，是不是没办法用这个模型进行训练

**Comment by Penge666** [comment]
> 尊敬的作者，您好。想请教一下如果我只有RGB图像，无法获得深度图信息，是不是没办法用这个模型进行训练

您好，请问一下megadepth训练时是否需要深度图呢？我用COLMAP处理处理的数据貌似没有深度图。

**Comment by 1135451439** [comment]
> 尊敬的作者，您好。想请教一下如果我只有RGB图像，无法获得深度图信息，是不是没办法用这个模型进行训练

你现在可以训练了吗？

**Comment by clw5180** [comment]
请教一下尊敬的作者 @ZJUCVG ，感谢

**Comment by guifenkuaipao** [comment]
> 尊敬的作者，您好。想请教一下如果我只有RGB图像，无法获得深度图信息，是不是没办法用这个模型进行训练

您好，请问您可以训练了吗

**Comment by zehongs** [comment]
一般来说不行。但是如果你会定义两张图的GT-对应关系的话就可以。

**Comment by clw5180** [comment]
> 请教一下尊敬的作者 @ZJUCVG ，感谢

不好意思，@错人了...

**Comment by clw5180** [comment]
作者大大为啥换号了：）

**Comment by the-cat-crying** [comment]
@zehongs 你好，pair_infos的信息怎么来的，请教一下。
