### ISSUE TITLE
Questions about groundtruth in the training process

### ISSUE THREAD

**Issue by Ov3RCoM3** [zju3dv/LoFTR#243]
Hello, thanks for your great work!
I want to know how the groundtruth labels are generated? In the paper, they are generated with pose matrices and depth images, but I didn't find it in the project codes. 
Thanks for your open-source code,
Liang

**Comment by zehongs** [comment]
https://github.com/zju3dv/LoFTR/search?q=gt
[src/loftr/utils/supervision.py](https://github.com/zju3dv/LoFTR/blob/4feac496c1eacebc49ce53793039a8162930935e/src/loftr/utils/supervision.py)
Some issues are also related to this topic.

**Comment by JiamuR** [comment]
> 您好，感谢您的出色工作！我想知道地面事实标签是如何生成的？在论文中，它们是用姿势矩阵和深度图像生成的，但我在项目代码中没有找到它。感谢您的开源代码，梁

Hello, do you know how ground truth labels are generated? I'm still not entirely clear on how they are produced. If you can help clarify this for me, I would greatly appreciate it.
