### ISSUE TITLE
Ground truth for training

### ISSUE THREAD

**Issue by GabbySuwichaya** [zju3dv/LoFTR#25]
Hi!  Thank you for releasing the code and the awsome paper. 

I am trying to re-implementing the training process.. And would like to ask some questions:

1. How do you generate ground truth for training? 
For example, if I used MegaDepth dataset, have you use the keypoints as a part of generating the ground truth matches of the dataset? Or did you consider the entire HxW of the coarse-scale (but, that will be lots of data)? 

2. From my understanding, the positional encoder of LoFTR has a fixed size of ChannelsxHxW.....So, at training your image size will be at a certain size... but this may be different from the inference phase .... How do solve this problem? 
For example, did you scale the positional encoder up? Or did you up/down-sampling the number of elements along with the HxW grids?   

3. Can you train the transformer of the coarse-scale separately from the fine-scale?  Or they need to be trained together....? 

4. I have noticed that you have used masks in training ... Could you guide how did you generate the mask?  Is the mask representing the edge structure of the GAT?   ....  

5. Are you still aim for releasing the codes on 06/10...? It would be great to see the official implementation... :)

**Comment by zehongs** [comment]
Hi Gabby,
1. We use 1/8-resolution grids. And the gt is calculated on-the-fly during training.
2. [Current implementation](https://github.com/zju3dv/LoFTR/blob/348ad897d4960108a1d59877c46edd22d3374385/src/loftr/utils/position_encoding.py#L11) of positional encoding already supports images with different shapes. And we do not need to up/down-sample the inputs.
3. From my experience, end-to-end training gives better results.
4. The mask enables training LoFTR with batch>1 on one GPU. The zeros in the mask indicate padded regions.
5. We'll try our best. 😂

**Comment by GabbySuwichaya** [comment]
Thanks for quick reply.. 
> Current implementation of positional encoding already supports images with different shapes. And we do not need to up/down-sample the inputs.
Is it because you have set up the max_shape ? 

> The mask enables training LoFTR with batch>1 on one GPU. The zeros in the mask indicate padded regions.
Can you elaborate what is the mask .... What is the padded regions? I am so sorry I am new to this pose encoder..

**Comment by zehongs** [comment]
The `max_shape` in our implementation is a trick to save PE as a buffer. It will prevent calculating the PE at every forward pass, which takes time to do computing and  memory allocation. You can also check out the mathematical definition of PE at [sup.pdf](https://zju3dv.github.io/loftr/files/LoFTR-suppmat.pdf). I think part 3.5 of *Attention is all you need* might also help you.

For the second question, check out the [code](https://github.com/zju3dv/LoFTR/blob/348ad897d4960108a1d59877c46edd22d3374385/src/utils/dataset.py#L83). Images in MegaDepth have different shapes and aspect ratios. Padding the image allows you to train LoFTR with batch>1.

**Comment by GabbySuwichaya** [comment]
I see. Thank you very much..... :)  
I will the issue now.
