### ISSUE TITLE
关于D2Net的未失真图像不再可用的问题

### ISSUE THREAD

**Issue by chen9run** [zju3dv/LoFTR#259]
你好，打扰了。
请问MegaDepth_v1提供的未失真图像是指MegaDepth_SfM _v1.tar.xz (tar.xz, 667 GB)里的还是MegaDepth_v1.tar.gz(198.80G)里的，十分感谢

**Comment by xmlyqing00** [comment]
Did you find the answer for it?

**Comment by ZizhuoLi** [comment]
你好！ 请问你那边还有MegaDepth_SfM _v1.tar.xz (tar.xz, 667 GB)的数据吗？
