### ISSUE TITLE
Where are the undistorted images provided by the MegaDepth_v1？ MegaDepth_SfM _v1.tar.xz (tar.xz, 667 GB)or MegaDepth_v1.tar.gz(198.80G)？

### ISSUE THREAD

**Issue by chen9run** [zju3dv/LoFTR#260]

**Comment by QiuhangLiu** [comment]
Hi! May I ask do you figure out this problem? I am confused about this either. Is the missing part of D2Net exactly corresponding to MegaDepth_SfM _v1.tar.xz (tar.xz, 667 GB)?
(We need to download both these 667GB and 198GB tar?)
