### ISSUE TITLE
Training stuck on: "initializing ddp: GLOBAL_RANK"

### ISSUE THREAD

**Issue by nonathecoda** [zju3dv/LoFTR#278]
I'm currently trying to train loftr outdoor_ds on 4 GPUs (RTX 3090), however when running the training I keep getting stuck at "initializing ddp: GLOBAL_RANK".

Has anyone experienced the same problem, and if yes, how did you solve it?

**Comment by nonathecoda** [comment]
the GPU I used was incompatible with CUDA 10

**Comment by Leon-xc** [comment]
hi~ i experienced the same problem. so how can i solve this problem? i will appreciate if you can help.

**Comment by nonathecoda** [comment]
hi! it's been some time so i don't remember too much, but I had to use a different GPU that was compatible with CUDA 10 (i used a cloud GPU via Genesis). But just google what CUDA versions your GPU is compatible with, hope it helps!

**Comment by Leon-xc** [comment]
> hi! it's been some time so i don't remember too much, but I had to use a different GPU that was compatible with CUDA 10 (i used a cloud GPU via Genesis). But just google what CUDA versions your GPU is compatible with, hope it helps!

thank you so much for your replying. i get it~
