### ISSUE TITLE
I want to know the `RESNETFPN.BLOCK_DIMS` while using ResNetFPN with RESOLUTION of (16, 4)

### ISSUE THREAD

**Issue by HuangDihe** [zju3dv/LoFTR#28]
Hi! Thank you for releasing the training code and the awsome paper.

I want to know the `RESNETFPN.BLOCK_DIMS` while using ResNetFPN with RESOLUTION of (16, 4).
Thank you very much.

more,
https://github.com/zju3dv/LoFTR/blob/master/train.py#L27
https://github.com/zju3dv/LoFTR/blob/master/train.py#L28
https://github.com/zju3dv/LoFTR/blob/master/train.py#L39
are these mistakes in coding?

**Comment by angshine** [comment]
Thanks for pointing out the mistake 👍 . We use the following `block_dims` for ResNetFPN _16_4 by default:

```python
_CN.LOFTR.RESNETFPN.INITIAL_DIM = 96
_CN.LOFTR.RESNETFPN.BLOCK_DIMS = [96, 128, 196, 256]
```

Note that the 16_4 version of LoFTR is not tested for the released version of the training code, feel free to open a issue if you met any problem.

**Comment by HuangDihe** [comment]
> Thanks for pointing out the mistake 👍 . We use the following `block_dims` for ResNetFPN _16_4 by default:
> 
> ```python
> _CN.LOFTR.RESNETFPN.INITIAL_DIM = 96
> _CN.LOFTR.RESNETFPN.BLOCK_DIMS = [96, 128, 196, 256]
> ```
> 
> Note that the 16_4 version of LoFTR is not tested for the released version of the training code, feel free to open a issue if you met any problem.

Thank you!
