### ISSUE TITLE
Problem of ScanNet Dataset pre-processing

### ISSUE THREAD

**Issue by rust-in** [zju3dv/LoFTR#29]
Hi, 

Thank you for your solid work!

I notice that you have computed the overlap score of image pairs in the given pre-processing file. Can you provide more details on how to compute this score? Or maybe release the pre-processing code of it. 

Thanks.

**Comment by angshine** [comment]
We follow the definitions of overlap scores in SuperGlue, and you could check out the Supplementary - E of their paper for more details. In detail, we compute the overlap score of ScanNet image pairs with dense depths and relative poses. A relative error of 0.15 is used for the depth consistency check. For MegaDepth, we use the overlap score [computed in D2-Net](https://github.com/mihaidusmanu/d2-net/blob/master/megadepth_utils/preprocess_scene.py).

**Comment by rust-in** [comment]
Thank you for reply！
