### ISSUE TITLE
training on custom dataset

### ISSUE THREAD

**Issue by sunset326** [zju3dv/LoFTR#295]
大佬，你好，非常感谢你们出色的工作。
我用一对自定义数据图像跑demo时，匹配效果很不错，能够匹配到的点很多。
我想做的是，只要能完成一对自己数据集图像的匹配就行。如果训练自定义数据集，请问训练过程能不能简化，只输入一对图像，不需要用到内外参数，不需要用深度图，评价模型时，用匹配得分（正确匹配的点/检测到的点）这个指标。

**Comment by sunset326** [comment]
非常期待诸位大佬的回复

**Comment by arthurdu98** [comment]
您好，大佬，我也是想在自己的数据集上训练这个模型。但是我找了好多帖子都没有发现怎么制作自己的数据集用于训练，我想问一下您是怎么做的呢？如果您能告诉我的话，我不胜感激。

**Comment by NaNtaisuike** [comment]
> 您好，大佬，我也是想在自己的数据集上训练这个模型。但是我找了好多帖子都没有发现怎么制作自己的数据集用于训练，我想问一下您是怎么做的呢？如果您能告诉我的话，我不胜感激。

佬，你好，我也想在自己的数据集上训练，请问一下您是怎么做的，求教

**Comment by liuzihua699** [comment]
hello，请问知道怎么训练自己的数据集了吗
