### ISSUE TITLE
Can you post the code?

### ISSUE THREAD

**Issue by Grungeby52** [zju3dv/LoFTR#3]
Hi,

Can I use it as an alternative to Akaze? 

Best Regards

**Comment by JiamingSuen** [comment]
1. The inference code will be release within this week, as detailed in [this](https://github.com/zju3dv/LoFTR/discussions/2) thread.
2. It will depend on the application. If the task is to calculate the relative pose between two images offline, then yes. If what you have in mind is a real-time SLAM system, it will take some engineering effort to 1) make LoFTR inference faster (currently at 116ms) 2) appropriately handle the large number of key point tracks across multiple images. We will also release more info about how to integrate LoFTR into a SfM pipeline in the future.
