### ISSUE TITLE
Adding Mask to Inference

### ISSUE THREAD

**Issue by shlomi-amitai** [zju3dv/LoFTR#32]
Hi, thanks for sharing your work!
I noticed you enable masking in training phase, does it possible also during inference?
(applying this change fails due to tensors size mismatch, feat_c0<->mask_c0)

**Comment by zehongs** [comment]
Yes, you can do that! The mask_c0 should have the same shape as that of feat_c0, which is 1/8 of the input image shape.
And may I ask why do you want to try this? I think inference without mask is more convenient, and they should have no difference😂

**Comment by shlomi-amitai** [comment]
Thanks, I’ll try that.
There are cases where there is a small overlap between the two images or the images are cropped, in these cases I’ve noticed that it is harder for the NN to match the correct features or somethings it finds features outside of the cropped area, where there are zeros. So I try to make it consider only part of the images plane.

**Comment by zehongs** [comment]
Oh, I see. I think you could also use the cropped CNN feature maps instead of using masks. That will save you a lot of GPU memory😃.

**Comment by marisancans** [comment]
> Thanks, I’ll try that.
> There are cases where there is a small overlap between the two images or the images are cropped, in these cases I’ve noticed that it is harder for the NN to match the correct features or somethings it finds features outside of the cropped area, where there are zeros. So I try to make it consider only part of the images plane.

I can also confirm this. If anyone else has similar problem, where there is a small overlap between images (like 20% - 40%), create a mask of that overlap region, resize it 1/8 to the shape you pass to model. I sometimes get even 10x more control points
