### ISSUE TITLE
difference between validation results and test results

### ISSUE THREAD

**Issue by zjhthu** [zju3dv/LoFTR#33]
Hi, for the indoor scenes, it seems that validation and test both use the scannet_test_1500 dataset, but their results are different even using the same model. What is the reason?

**Comment by angshine** [comment]
Hi, sorry for the late reply! The configs for training(&evaluation) and testing are different. The behavior is explained in our [ScanNet testing config](https://github.com/zju3dv/LoFTR/blob/master/configs/loftr/indoor/scannet/loftr_ds_eval.py):
```python
""" A config only for reproducing the ScanNet evaluation results.
We remove border matches by default, but the originally implemented
`remove_border()` has a bug, leading to only two sides of
all borders are actually removed. However, the [bug fix](https://github.com/zju3dv/LoFTR/commit/e9146c8144dea5f3cbdd98b225f3e147a171c216)
makes the scannet evaluation results worse (auc@10=40.8 => 39.5), which should be
caused by tiny result fluctuation of few image pairs. This config set `BORDER_RM` to 0
to be consistent with the results in our paper.
"""
```

You would get consistent results if using this config for validation.

**Comment by zjhthu** [comment]
thx, the `BORDER_RM` indeed leads to the difference.
