### ISSUE TITLE
Easy way to emulate COTR?

### ISSUE THREAD

**Issue by ducha-aiki** [zju3dv/LoFTR#36]
Hi,

Is there am (easy) way of supplying LOFTR with the "query points" on one image in order to get the most probable matching locations in the other image?

**Comment by zehongs** [comment]
Hi Dmytro,
I'm afraid there is no easy way. From my personal experience, using "query points" with the released model and weights is unlikely to give you perfect results. 
In fact, we have tried a variant called LoFTR-SPP in the IMW-Challenge. Please refer to our [technical report](https://zju3dv.github.io/loftr/files/LoFTR_IMC21.pdf) for more details. However, we have no plan to release the code and model currently.

**Comment by ducha-aiki** [comment]
Thank you for the quick answer!
