### ISSUE TITLE
Ground-truth labels on my dataset

### ISSUE THREAD

**Issue by 1962975362** [zju3dv/LoFTR#37]
Hi, authors
if I want train the model on my own dataset, how can I get the Ground-truth label.   

I see you said 'We use dense depth maps and camera parameters to compute ground-truth correspondences. The depth maps are provided by depth sensor (ScanNet) and MVS system (MegaDepth).'    the camera parameters is ?

**Comment by zehongs** [comment]
Hi,
The ground-truth correspondence label is calculated on-the-fly. What you need to provide is the dense depth map and camera parameters.
And there are extrinsic parameters (i.e. relative R, t that reveal camera motion) and intrinsic parameters (focal length, principal point that reveal projective distortion).

**Comment by 1962975362** [comment]
thanks, Does the camera parameter refer to the real transformation matrix or other parameters?

**Comment by zehongs** [comment]
I'm not sure about what you're referring to. Maybe this [opencv documentation](https://docs.opencv.org/4.5.2/d9/d0c/group__calib3d.html) would help you!

**Comment by 1962975362** [comment]
thank a lot!

**Comment by 1962975362** [comment]
I have a small question, whether it is possible to train the model with only one data set and only use the MegaDepth data set. Is it necessary to provide only the depth map without the camera pose parameters?

In the code, the data processing part：

    def _build_concat_dataset(
        self,
        data_root,
        npz_names,
        npz_dir,
        intrinsic_path,
        mode,
        min_overlap_score=0.,
        **pose_dir=None**
    ):
        datasets = []
        augment_fn = self.augment_fn if mode == 'train' else None
        data_source = self.trainval_data_source if mode in ['train', 'val'] else self.test_data_source
        if str(data_source).lower() == 'megadepth':
            npz_names = [f'{n}.npz' for n in npz_names]
        for npz_name in tqdm(npz_names,
                             desc=f'[rank:{self.rank}] loading {mode} datasets',
                             disable=int(self.rank) != 0):
            # `ScanNetDataset`/`MegaDepthDataset` load all data from npz_path when initialized, which might take time.
            npz_path = osp.join(npz_dir, npz_name)
            **if data_source == 'ScanNet':**
                datasets.append(
                    ScanNetDataset(data_root,
                                   npz_path,
                                   intrinsic_path,
                                   mode=mode,
                                   min_overlap_score=min_overlap_score,
                                   augment_fn=augment_fn,
                                   **pose_dir=pose_dir))**
            **elif data_source == 'MegaDepth':**
                datasets.append(
                    MegaDepthDataset(data_root,
                                     npz_path,
                                     mode=mode,
                                     min_overlap_score=min_overlap_score,
                                     img_resize=self.mgdpt_img_resize,
                                     df=self.mgdpt_df,
                                     img_padding=self.mgdpt_img_pad,
                                     depth_padding=self.mgdpt_depth_pad,
                                     augment_fn=augment_fn,
                                     coarse_scale=self.coarse_scale))
            else:
                raise NotImplementedError()
        return ConcatDataset(datasets)
**When processing the MegaDepth data set, there is no camera pose parameter**

**Comment by zehongs** [comment]
Yes, we train indoor model with scannet dataset only, and outdoor model with megadepth only.
The data organization is not the same. For megadepth, intrinsic and extrinsic parameters are in npz.

Check this:
https://github.com/zju3dv/LoFTR/blob/261baf641cb9ada07dd9746e420ada7fe8a03152/src/datasets/megadepth.py#L92
