### ISSUE TITLE
Some question about the coarse

### ISSUE THREAD

**Issue by 1962975362** [zju3dv/LoFTR#39]
hi,
I have some questions about the coarse supervision

in superbvision.py 

1、about mask
if 'mask0' in data:
        grid_pt0_i = mask_pts_at_padded_regions(grid_pt0_i, data['mask0'])
        grid_pt1_i = mask_pts_at_padded_regions(grid_pt1_i, data['mask1'])
![image](https://user-images.githubusercontent.com/45714180/127262208-a5916279-7705-4479-9375-467a973d3aee.png)
Where is the mask obtained? The data is color ，depth， pose and internal reference
2、  check if mutual nearest neighbor
    w_pt0_c_round = w_pt0_c[:, :, :].round().long()
    nearest_index1 = w_pt0_c_round[..., 0] + w_pt0_c_round[..., 1] * w1
    w_pt1_c_round = w_pt1_c[:, :, :].round().long()
    nearest_index0 = w_pt1_c_round[..., 0] + w_pt1_c_round[..., 1] * w0
I don’t quite understand this step, can you give me some interpretation?

3、warp grids
    # create kpts in meshgrid and resize them to image resolution
    grid_pt0_c = create_meshgrid(h0, w0, False, device).reshape(1, h0*w0, 2).repeat(N, 1, 1)    # [N, hw, 2]
    grid_pt0_i = scale0 * grid_pt0_c
    grid_pt1_c = create_meshgrid(h1, w1, False, device).reshape(1, h1*w1, 2).repeat(N, 1, 1)
    grid_pt1_i = scale1 * grid_pt1_c

how create kpts(key points)?  

Hope to answer, thank you

**Comment by zehongs** [comment]
Hi,
1. The mask is not necessary when training ScanNet, since all image pairs will be resized to 640x480.
2. Given warped points at coarse-level, we use `i = y*W + x` to transfer (x, y) position into flattened index. The operation is performed for both directions of image0-to-image1 and image1-to-image0.
3.  Check this [kornia documentation](https://kornia.readthedocs.io/en/latest/_modules/kornia/utils/grid.html).

**Comment by 1962975362** [comment]
thanks a lot！！
In detail, how to compute the overlap score of ScanNet image pairs with dense depths and relative poses？
Is there a corresponding processing file？

**Comment by zehongs** [comment]
You're welcome! We followed SuperGlue for this part. However, since the code is coupled with some internal infrastructure, we don’t have recent plans to release the code currently.

**Comment by 1962975362** [comment]
Can you give me some tips, I want to make my own data set for training

**Comment by JiamingSuen** [comment]
> Can you give me some tips, I want to make my own data set for training

![image](https://user-images.githubusercontent.com/8616975/127489153-0d186a51-d8e6-424a-a5f4-146d6cbb1319.png)
Please follow the instructions in the SuperGlue paper.
