### ISSUE TITLE
Some quetions about LoFTR

### ISSUE THREAD

**Issue by davidz123** [zju3dv/LoFTR#4]
Hi， I tried your code and model, and the result is beyond me expectation.
I still got two questions about LoFTR:
  (1) Why not fed colored images into network as they have more information especially in nature scene? 
  (2) For some reason, I do not have annotations of corresponding points, Is there any WEAK-supervision solution that be used to train LoFTR?
Thanks for your work again, and Looking forward to your reply : )

**Comment by JiamingSuen** [comment]
Thanks for the questions. 
1. Most previous works in this field use gray images as input. According to our past experiences, the matching results with gray images do not degrade compared to using color images.
2. Dense correspondence annotations can be obtained by COLMAP as in MegaDepth, or a depth sensor and the corresponding camera pose as demonstrated in ScanNet. A weak-supervision variant of LoFTR is potentially possible (but not easy) with some research efforts that yet to be explored in the future.

BTW, you are welcomed to use the discussion panel to discuss questions related to the paper (i.e., not the implementation). I'll close this issue for now, feel free to open a new discussion thread😃.
