### ISSUE TITLE
Auxiliary losses in training statge

### ISSUE THREAD

**Issue by chenghegao4556** [zju3dv/LoFTR#40]
Hi, thanks for your awesome work, have you tried to add  Auxiliary losses( like other transformer based model, DETR) in the training statge? If yes, would that improve the matching performance？

**Comment by zehongs** [comment]
Hi, 
from my understanding, it's not straight forward to use auxiliary losses in LoFTR, since there is no design like transformer decoder in our work.

**Comment by chenghegao4556** [comment]
Hi, i mean add loss module at the end of each "cross attention" module, for coarse matching stage.

**Comment by zehongs** [comment]
Hi, I think further experiments need to be done. Unfortunately, we're working on other projects currently. So, if you have the results, please let us know! I'm curious about the results.

**Comment by chenghegao4556** [comment]
Thanks for your reply! I would like to, but i do not have enough GPUs to train...
