### ISSUE TITLE
supervision for positions do not have valid depth in GT depth map

### ISSUE THREAD

**Issue by chenghegao4556** [zju3dv/LoFTR#44]
Hi, i have a question about the coarse level matching supervision for positions do not have valid depth in GT depth map. For example, some points on the top of the tower.
![image](https://user-images.githubusercontent.com/54935226/128453275-eaffcc98-0a20-4346-a9f5-6b352c88186c.png)
Will these matches with unvalid depth be supervised as un-matched? or just ignore these matches？

**Comment by zehongs** [comment]
Hi, I believe they will be ignored.
