### ISSUE TITLE
What is the accuracy if training with 4 GPUs?

### ISSUE THREAD

**Issue by Tangshitao** [zju3dv/LoFTR#46]
I train the model with 4 GPUs and got 51AP of AUC20 at epoch 15. Is it normal?

**Comment by zehongs** [comment]
Megadepth or ScanNet？

**Comment by Tangshitao** [comment]
scannet

**Comment by zehongs** [comment]
So there is an about 7-point AUC@20 gap from the released LoFTR-indoor model. 
Are you using the DS config? Are all other settings the same except for the batch-sizes(gpus) ?

**Comment by Tangshitao** [comment]
Yes, but I only train it for 15 epoch. Can you provide the result of training with 4 and 8 gpus?

**Comment by JiamingSuen** [comment]
It will take a much longer training time (several days) to meet the original performance of LoFTR on ScanNet with 4 GPUs. We haven't done any experiment with 4 GPUs so unfortunately we can't provide the results.
