### ISSUE TITLE
Unable to reproduce inference results

### ISSUE THREAD

**Issue by howard5758** [zju3dv/LoFTR#48]
Hi,

First I'd like to sincerely thank the author for sharing this amazing work.
When I tried the provided colab with default setting (indoor), the resulting plot was quite poor.
![Screenshot 2021-08-16 185650](https://user-images.githubusercontent.com/33792664/129643392-4b9e8563-4673-4b06-b066-5b58ac1f3c78.png)

Similar problem occurred when I cloned the repo and tested on both indoor and outdoor pairs on 
indoor_ds.ckpt and outdoor_ds.ckpt

Can anyone advise on this?
Thank you very much!

**Comment by JiamingSuen** [comment]
Hi @howard5758, a recent bug fix (3955e99 and #41) breaks the compatibility of the released model weights. We will fix this issue very soon and release the new models, thanks for the heads up.

**Comment by howard5758** [comment]
Understood. Thank you so much for the quick response and the information :)

**Comment by angshine** [comment]
Hi, this issue has been fixed in the most recent commit.

**Comment by howard5758** [comment]
Hi, thanks for the prompt actions.

I cloned the repo again and first encountered the following error:
<img width="473" alt="loftr_error1" src="https://user-images.githubusercontent.com/33792664/129741747-b2aba261-2f01-4e21-84f0-f2dd9265476c.PNG">
I removed the line "temp_bug_fix=config['coarse']['temp_bug_fix'])" and it still gave similar inference result as yesterday.
I then downloaded the new indoor_ds model you shared earlier, but saw a bunch of missing keys in state_dict and was unable to perform inference.
<img width="657" alt="loftr_error2" src="https://user-images.githubusercontent.com/33792664/129742116-3b934d8b-f358-4ab5-862f-7f6050d74617.PNG">

Really appreciate your help :)

**Comment by angshine** [comment]
Hi @howard5758, can you share the script(`mytest.py`) and the config you are using? I think this relates to a misconfiguration of the project (e.g. mixing old & new files🤔).

**Comment by howard5758** [comment]
Hi @angshine , mytest.py is basically the exact same code from demo_single_pair.ipynb 
The only part I modified is commenting out "temp_bug_fix=config['coarse']['temp_bug_fix'])" in src/loftr/loftr.py
Currently the provided colab is still giving me the keyerror:
<img width="531" alt="loftr_error3" src="https://user-images.githubusercontent.com/33792664/129758602-857e4555-017a-4206-8784-57c6a6ab5a2d.PNG">
Can you kindly double check the colab maybe then I can directly follow the steps there.
Thank you very much!

**Comment by angshine** [comment]
Hi, sorry for the inconvenience, and thank you for your time! I have updated the code and tested the colab and `demo_single_pair.ipynb` results, and they all work appropriately now.  Just make sure you use `temp_buf_fix=True` with the new ckpt. We will polish the logic in later releases.

**Comment by howard5758** [comment]
Hi, I can confirm the provided colab work appropriately. Thank you so much for the help!

**Comment by GabbySuwichaya** [comment]
Hi! Just wonder if the new trained weight is updated ?

**Comment by JiamingSuen** [comment]
The updated weight is in the google drive folder [here](https://drive.google.com/drive/folders/1DOcOPZb3-5cWxLqn256AhwUVjBPifhuf?usp=sharing)
![image](https://user-images.githubusercontent.com/8616975/131662268-edd6317e-b653-4114-9e53-8bb8d9e5b555.png)

**Comment by GabbySuwichaya** [comment]
Thanks! Such a good news. Are they all updated ? All the cases?

**Comment by xmba15** [comment]
@JiamingSuen Can you also update outdoor_ds.ckpt? I still see the problem mentioned above with outdoor_ds.ckpt.
