### ISSUE TITLE
Poor accuracy

### ISSUE THREAD

**Issue by Zumbalamambo** [zju3dv/LoFTR#5]
I tested the code in some random image pairs. The results are extremely bad. How do I improvise the accuracy of the inference?

**Comment by noone-code** [comment]
@Zumbalamambo Could you show the visualizations ? I'm curious about it.

**Comment by zehongs** [comment]
Hi @Zumbalamambo, what config and pretrained model did you use? Could you also post the image pair in this issue? Thanks!

**Comment by JiamingSuen** [comment]
After some double-checking, we are confident that the code and the weights provided are correct.
Since @Zumbalamambo is not responding for 4 days, I'm closing this issue for now. Feel free to reopen it with more information (e.g. the input image pair, the results produced by LoFTR, etc.).
