### ISSUE TITLE
Conda pip error and how to fix it

### ISSUE THREAD

**Issue by ducha-aiki** [zju3dv/LoFTR#52]
On my version of pip, the environment creation is crashing with the following error:

```AttributeError: 'FileNotFoundError' object has no attribute 'read'```

According to this [SO answer](https://stackoverflow.com/a/68586065/1983544), the issue is because of pip interface change and one needs to remove 'file:' or to  provide an absolute path to requirements.txt 

```
  - pip:
    - -r requirements.txt
```

**Comment by zehongs** [comment]
Thank you! We fixed it in https://github.com/zju3dv/LoFTR/commit/fc4871e9abb2e83b96173f4a88fe79dcc42771fc .
