### ISSUE TITLE
Different image resolution?

### ISSUE THREAD

**Issue by marisancans** [zju3dv/LoFTR#54]
Hi there, 
I wanted to use different image resolution, my size is 2307x3466, I know that its quite a lot.
Do I have to re-train the network in order to use such resolution (network breaks if anything other than 640, 480 is used)
Do I really need to resize the image? In my mind, higher resolution means better feature matching, but is that correct?
Thanks

**Comment by zehongs** [comment]
Hi,
To use other resolutions, you need to set the picture height and width to a multiple of 8.
I think you can try different resolutions and use the best.

**Comment by viv696** [comment]
also, the maximum resolution has to be lower than 2048
