### ISSUE TITLE
Matching threshold used in training step

### ISSUE THREAD

**Issue by chouscode** [zju3dv/LoFTR#6]
Hi, thanks for your great work. 
After reading your paper, I have some questions regarding what is the match threshold set to in training step.
When I tried to set match threshold to 0.2 like your paper，I found there will be 0 matches from coarse mathcing layer, and fine matching layer and fine-level supervision  will lose efficacy. So, should the threshold be set to a smaller value, such as 0.0, during training？

**Comment by zehongs** [comment]
Hi, thanks for your interests!
1. For coarse-level, the outdoor-DS model reaches 0.56@auc10 after 1 epoch of training on MegaDepth. So I believe there is no need to set the threshold to a smaller value.  
2. For fine-level, we sample some gt coarse matches and pad them to the coarse-level prediction during training. This will make the fine-level supervision effective all the time.

**Comment by chouscode** [comment]
Thanks for your reply. I got it.

**Comment by HuangDihe** [comment]
@chouscode hi, I got the same problems. Could you tell me more details?

**Comment by chouscode** [comment]
Hi,HuangDihe，

Surely, could you please briefly describe your problem




Best Regards

Yuhao



-----原始邮件-----
发件人:HuangDihe ***@***.***>
发送时间:2021-05-18 13:36:29 (星期二)
收件人: zju3dv/LoFTR ***@***.***>
抄送: chouscode ***@***.***>, Mention ***@***.***>
主题: Re: [zju3dv/LoFTR] Matching threshold used in training step (#6)






@chouscode hi, I got the same problems. Could you tell me more details?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.





周宇豪 研究生
现代光学仪器国家重点实验室
浙江大学光电科学与工程学院
地址：浙江省杭州市西湖区浙大路38号教三311室
邮编：310027
电话：13777879296

**Comment by HuangDihe** [comment]
> Hi,HuangDihe， Surely, could you please briefly describe your problem Best Regards Yuhao

Could you tell me how do you reproduce the coarse level training? thanks

**Comment by GabbySuwichaya** [comment]
I have the same problem ... Or did you optimize on the `conf_matrix` by choosing the index based on the ground truth matches?
