### ISSUE TITLE
Aachen test code

### ISSUE THREAD

**Issue by cvlab-flash** [zju3dv/LoFTR#61]
hi, thanks for your great work, will you release the test code for Aachen localization benchmark?

**Comment by zehongs** [comment]
Hi, I'm very sorry that we don't have plan for the test code refactorization currently. 
The test code of the visual-localization-benchmark is partly based on [DualRC-Net](https://github.com/ActiveVisionLab/DualRC-Net/tree/master/aachen_day_and_night), maybe this would help you.
