### ISSUE TITLE
Update for the trained weights ?

### ISSUE THREAD

**Issue by GabbySuwichaya** [zju3dv/LoFTR#64]
Hello, 
Thank you for the great works.

I have tried to use your method for outdoor images.
However, after bug fixing, it seems that the weight "outdoor_ds.ckpt"  is not working as good as it used to be... 
Therefore, could you please provide the update for the "outdoor_ds.ckpt"  as well?

**Comment by angshine** [comment]
Hi, may I ask you which config file and script are you using? The performance should not change as long as `cfg.LOFTR.COARSE.TEMP_BUG_FIX ` is set to `False`. The outdoor model with the positional encoding bug fixed does not lead to better performance, so we haven't released it yet.

**Comment by GabbySuwichaya** [comment]
Hi! Thanks for your reply.

 Here I have tried running the work before and after bug-fix .... 
```
Before>> Bug-Fixed (COARSE.TEMP_BUG_FIX = False) << First (Top) image 
After  >>  Bug-Fixed (COARSE.TEMP_BUG_FIX = True)  << Second (Bottom) image
``` 
However, after bug fixing, I get a worse result.

- Could you please explain why using the  `COARSE.TEMP_BUG_FIX = True` ... then I get the worse result when actually the formulation is correct? 

- Or is there any possibility that I might have set anything wrong? 


![normal_image_bug_false-before-bug-fixing](https://user-images.githubusercontent.com/49115268/132835157-8d51a0bc-0f1c-4c79-a006-788bf7c16dd9.jpg)  
![normal_image_bug_true-after-bug-fixing](https://user-images.githubusercontent.com/49115268/132835180-d22e15d5-0679-44cb-a708-4ed68b62fb38.jpg)

**Comment by GabbySuwichaya** [comment]
Thanks... I will close the issue now.
