### ISSUE TITLE
Deployment on KITTI dataset.

### ISSUE THREAD

**Issue by kkoledic1212** [zju3dv/LoFTR#66]
Could this model work on KITTI dataset. I understand that the model uses ground truth depth for training which KITTI does not have much of. However, do you have any knowledge would a model trained on MegaDepth perform well on KITTI, i.e. how good is generalization to other datasets.

If not, could it be trained on some other automotive dataset similar to KITT?

**Comment by zehongs** [comment]
Hi,
The outdoor model should work on most outdoor scenarios.
You can train LoFTR on datasets with depth-maps.
