### ISSUE TITLE
Problem Dealing with ScanNet Dataset

### ISSUE THREAD

**Issue by MichiganLu** [zju3dv/LoFTR#67]
Dear friend,

I really appreciate your work and have spent a big chunk of my time testing and optimizing. I have already done some pruning of the network but need to finetune with the ScanNet dataset, where the problems come in. 
Firstly, I notice that ScanNet occupies more than 1.2 Tera Bytes of disk, which is a pain to download. Since I am only finetuning the model, not like training from scratch, is it really necessary to download the entire dataset? If not, could you please give me suggestion on which part to download, or provide a slice of the processed ScanNet data (maybe two three gigabytes are good enough) for direct download if possible(like Google drive, Dropbox). 
Second, since I see several export option for the ScanNet dataset, i.e. depth image, color image, pose, extrinsic, I would like to know if need to export all? And how do I arrange the data directory so that the training script will work without error? For example, arrange it like data/depth_img, data/color_img, etc. Again, it will be very nice if you can provide a slice of the data directly.
Third, a technical question. In your transformer skip connection (just like ResNet), I notice that you concatenate the input with the transformer attention output before feeding to feed forward network(so the dimension change from 256 channels to 512 channels). In a normal transformer setup, people will just add them instead of concatenation. May I know why you do that? From the optimization perspective, a linear layer of nn.Linear(512, 512) yields much more parameters and FLOPs than a nn.Linear(256,512). I am thinking that if all of the linear layer can be revised to 256 channel input, you may save like 500K parameters.
Final question. Is it possible to finetune(train) with one 1080Ti? I mean as a student, I can live with a longer training time. But I am not sure if the RAM of my GPU is enough. Will it crash in a minute and become totally untrainable?
Sorry for bringing up some many questions. It will definitely help me if you can give me some direction. Thanks. 

Richard

**Comment by zehongs** [comment]
Hi,
We really appreciate your efforts!
1. It makes sense to only use a subset of ScanNet when 'fine-tuning' LoFTR. My suggestion is to randomly sample some sequences from the train-set.
2. Yes. The data organization is the same as in `scannet_test_1500`.
3. We haven't done experiments to compare them. Intuitively, `concat + linear` might give better results than `add + linear`.
4. The major factor behind the number of GPUs is the batchsize. For training from scratch, the minimum recommended value is bs=8. In terms of fine-tuning, I'm afraid one 1080Ti is not enough.
