### ISSUE TITLE
The memory  leakage

### ISSUE THREAD

**Issue by zwyking** [zju3dv/LoFTR#69]
Hi, I found an issue reported by pytorch that the code may have a memory leakage. It would be caused by a plot function.
![QQ截图20210924100721](https://user-images.githubusercontent.com/45560490/134607706-b0b1f6e2-b7b4-4bc4-8ea8-fdd9ef6e8691.png)

**Comment by zehongs** [comment]
We close all figures at the end of validation epoch. So, don't worry about this!

**Comment by zwyking** [comment]
Ok.
