### ISSUE TITLE
no results appeared !

### ISSUE THREAD

**Issue by trungpham2606** [zju3dv/LoFTR#7]
Dear @JiamingSuen 
Thank you for sharing such a great work !
I was testing random pair of images and this is the result I got:
![image](https://user-images.githubusercontent.com/35657426/114963088-28b27880-9e96-11eb-8b1e-95379de51ae9.png)

I'm wondering that maybe LoFTR is suffering the same problem as SuperGlue that it cant detect matching when the image is rotated more than 45 degree ?
I was using the indoor_ds weights.

**Comment by zehongs** [comment]
Hi, I believe the reason is that we didn't train LoFTR with pairs that exhibit extreme rotation. We only downsampled the image pairs from MegaDepth and ScanNet, and the purpose of which was to reduce GPU memory.
By the way, for matching pairs with extreme rotation and scaling, you can refer to our Neurips'19 work [GIFT](https://github.com/zju3dv/GIFT).

**Comment by JiamingSuen** [comment]
> Hi, I believe the reason is that we didn't train LoFTR with pairs that exhibit extreme rotation. We only downsampled the image pairs from MegaDepth and ScanNet, and the purpose of which was to reduce GPU memory.
> By the way, for matching pairs with extreme rotation and scaling, you can refer to our Neurips'19 work [GIFT](https://github.com/zju3dv/GIFT).

In addition to Zehong's reply, I would like to point out that LoFTR (and SuperGlue) learns the matching priors (i.e., the distribution of matches between the image pair) from the **training data**, which means that it can handle rotations only exhibited in the training set. In most real-world scenarios like in ScanNet and MegaDepth, there won't be such extreme rotation variations like the image pair given (over 90 degrees). With that being said, handling extreme rotation changes is indeed another interesting research topic beyond the major focus of LoFTR. We recommend you to check out our work GIFT and more recent work [LISRD](https://github.com/rpautrat/LISRD) for this purpose.

**Comment by trungpham2606** [comment]
Thank @JiamingSuen @zehongs for your quick and detailed response. I'm gonna have a look at GIFT and LISRD.
