### ISSUE TITLE
Aachen数据集测试

### ISSUE THREAD

**Issue by ssssjiang** [zju3dv/LoFTR#70]
你好！
（因为我英文不太好，担心词不达意，还是用中文提问了嗷）
我用Aachen数据集的图像作为输入，并使用了图像的原始大小，在输入的第一张图像（1600 x 1067）,它在经过CNN部分时，大小依次变为（800 x 534）（400 x 267）（200 x 134）,在上采样阶段大小变为（400 x 268），此时因为267和268是不对齐的，程序崩溃(resnet_fpn.py line112  'x2_out = self.layer2_outconv2(x2_out+x3_out_2x)')。
我很想解决这个问题，但是我对深度学习的了解非常少，不敢随意改动…或许你们可以告诉我这个情况应该怎么办吗？如果我想对Aachen数据集进行测试，我该怎么处理一下？

打扰了嗷😢

**Comment by zehongs** [comment]
hi，你可以将输入图片resize（或者cropping）到8的倍数，之后再映射回原来的图片坐标系就好了！
