### ISSUE TITLE
Memory leak.

### ISSUE THREAD

**Issue by Qing-WANG-KIT** [zju3dv/LoFTR#78]
Hello, during my training, the cpu memory keeps increasing. My 128g memory was full in less than one epoch. Is it possible for a memory leak in the code?

**Comment by leon5678** [comment]
> Hello, during my training, the cpu memory keeps increasing. My 128g memory was full in less than one epoch. Is it possible for a memory leak in the code?

hi, did you solve the problem？ something similar happens to me.

**Comment by tomsiu** [comment]
I encounter the same issue. May have your advises on how to solve the memory leak problem? Thank you very much. I am doing streaming on 320x180 image size ,and the memeory keep accumulating slowly

**Comment by xml-0506** [comment]
I have the same problem, during training, the memory slowly accumulates from 13 to 32 or even more, causing the training to be interrupted
