### ISSUE TITLE
About scannet training

### ISSUE THREAD

**Issue by zwyking** [zju3dv/LoFTR#79]
Hi, recently I  run the training code using the scannet dataset, while it reports a issue about the parallel_load_data.

![QQ截图20211006154304](https://user-images.githubusercontent.com/45560490/136161743-869386c8-4d3d-4b66-a71c-2d6846ec18c0.png)

**Comment by zwyking** [comment]
I run the code following the readme.txt. 
#########
cd root_path
sh scripts/reproduce_train/indoor_ds.sh
#########

**Comment by zehongs** [comment]
I'm sorry for the late reply.  ​Have you solved the problem yet?
It seems that you installed the conda environment and launched the script in our default way. And this should work just fine.

**Comment by zwyking** [comment]
yeah，i didn't use the data_parallel and works.
