### ISSUE TITLE
About the ground-truth labels

### ISSUE THREAD

**Issue by atztao** [zju3dv/LoFTR#8]
This is a good job, but i'm very Interested in that how to make the ground-truth labels. I found your macth pair results similar to the SP+SG, you used the SuperPoint labels?

**Comment by zehongs** [comment]
This is a very good question. And we didn't use any detector labels. As stated in the paper (3.5), mutual nearest neighbors of 1/8-resolution grids are selected as coarse-level labels, and sub-pixel correspondences are the fine-level labels.

**Comment by atztao** [comment]
按你文中所示用了[Qianqian Wang, Xiaowei Zhou, Bharath Hariharan, and Noah Snavely. Learning feature descriptors using camera pose supervision. In ECCV, 2020. 5]该方法，通过有relative pose利用极线约束来进行学习描述子。

**Comment by zehongs** [comment]
We didn't apply epipolar loss proposed in CAPS to learn descriptors. 我们没有使用CAPS提出的极线损失函数来学习描述子。

**Comment by atztao** [comment]
Of course, you constructed a loss to  find the match pairs.

**Comment by zehongs** [comment]
Oh, @atztao  I'm sorry I think finally understand your question based on your edited description. 
We use dense depth maps and camera parameters to compute ground-truth correspondences. The depth maps are provided by depth sensor (ScanNet) and MVS system (MegaDepth).

**Comment by atztao** [comment]
Ok,  good answer.
