### ISSUE TITLE
a simple question about saving npzfile

### ISSUE THREAD

**Issue by HuangDihe** [zju3dv/LoFTR#83]
Hi, when I use [d2net-preprocess](https://github.com/mihaidusmanu/d2-net/blob/master/megadepth_utils/preprocess_scene.py) to reproduce the npz file, I got NpzFile object using np.load(path, allow_pickle=True).
However, I got dict object when I read your npz. I want to know how you save the npzfile

**Comment by JiamingSuen** [comment]
We use `np.savez_compressed()`.

**Comment by HuangDihe** [comment]
Thanks!
