### ISSUE TITLE
Reproduce Visual Localization Work

### ISSUE THREAD

**Issue by Zhongyuan-Li** [zju3dv/LoFTR#9]
Thanks for amazing work!
     About the reproduction for the visual localization work with hloc, I have some confusions.
     As for my understanding, loftr will give a match result include local keypoints0, local keypoint1 and their matching confidence although the matching process is "local features" free. So the local key point locations are concerned with the image pairs. Different image pairs may produce different keypoints. Like pair (image a, image b) and pair (image a, image c) may result totally different keypoints distribution on image a.
     During the sfm procedure in hloc,,  triangluation process requires long keypoints tracks to ensure the 3D points' quality. So how to handle this situation while different keyframe pairs produce variance keypoints for one keyframe.  
     Is there any strategy or principle to combine the keypoints which are close distributed?

**Comment by Zhongyuan-Li** [comment]
Thanks for quick reply.  It seems like continuous keyframes can still produce similar keypoints distribution due to round() function.
Following the localization strategy, the standard flow is: image retrieval -> 2D-2D match -> 3D-2D pnp -> pose result. Owing to round() during structure from motion,  3D points are binding with integer keypoints in keyframes. So during localization, how to handle the correspondence between 3D points and the new sub-pixel db keypoints or maybe the sup-pixel strategy is only used in query images ?

**Comment by zehongs** [comment]
Correct. For LoFTR, we use sub-pixel strategy only for query images currently.

**Comment by Zhongyuan-Li** [comment]
Thanks a lot. I'll have a try!

**Comment by zehongs** [comment]
No problem 👏

**Comment by K0stIa** [comment]
Hi @Zhongyuan-Li @zehongs ,
I have a question about this part 
"we use sub-pixel strategy only for query images currently."

Could you explain this part in more detail?

**Comment by zehongs** [comment]
Hi,
For visual localization, one needs to first build a map with database images, and then establish correspondences for database-query images. Specifically, to find correspondences of the database points  and query points. 
Here, we round the point location when building database map. And we use sub-pixel strategy when computing the database-query crrespondences.

**Comment by Kevin-Kai96** [comment]
hi,@zehongs,i have a problem when I try to reconstruction my custom data by hloc+loftr. I used round() to save the result of loftr and inserted the pixel point as keypoint. Also I inserted the matching correspondence of two images. However, I got an error in pycolmap as check failed: bundle_adjuster.Solver(&reconstruction). Can you help to solve it if you have any experience? Many thanks

**Comment by zehongs** [comment]
Hi, I have not encountered this problem. Maybe you can reduce the amount of data, and manually check if the output files are all correct for COLMAP.
