### ISSUE TITLE
dataset preparation for retraining/fine tuning 

### ISSUE THREAD

**Issue by whh14** [zju3dv/LoFTR#93]
Hi there,

Is is possible to have more documentation on dataset preparation for fine tuning/retraining.  

The idea is for example say, I have a dataset of birds images, and I would to fine tune/retrain so that the LoFTR model for tracking features of birds.

so the first step would be first process the birds images with LoFTR to get some match points pairs. then I filtered out non birds matching points, and remove the incorrect matching points. This becomes the custom dataset that  I would like to fine tune

I guess the main question is what is the best way of amending the training pipeline to take in such dataset?   Thanks a lot

**Comment by molchanov-vs** [comment]
Hi!
Have you succeeded in your own dataset preparation for tune/retrain LoFTR?
