### ISSUE TITLE
a simple question about saving npzfile

### ISSUE THREAD

**Issue by HuangDihe** [zju3dv/LoFTR#98]
Hi, I have tried to use np.savez_compressed() to save the npz and read data from the npz I created, it still is NpzFile object, not dict object.
[this issue](https://github.com/zju3dv/LoFTR/issues/83)

**Comment by HuangDihe** [comment]
I can use the key to read values from the object. However, it is a NpzFile object, not a dict object

**Comment by HuangDihe** [comment]
`np.savez_compressed(
    os.path.join(args.output_path, "%s.npz" % scene_id),
    image_paths=image_paths,
    depth_paths=depth_paths,
    intrinsics=intrinsics,
    poses=poses,
    pairs_info=pairs_info,
)`

**Comment by zehongs** [comment]
> I can use the key to read values from the object. However, it is a NpzFile object, not a dict object

I think it is by design😂

**Comment by HuangDihe** [comment]
> > I can use the key to read values from the object. However, it is a NpzFile object, not a dict object
> 
> I think it is by design😂

My question is how to save the npz so that I can get a dict object when I read it.

**Comment by zehongs** [comment]
1. use `dict(np.load(path))`
2. For related question, I suggest you read numpy or python documentation, since it is certainly beyond the scope of this repo.

**Comment by Bailin-He** [comment]
May I ask how the npz file was generated？

**Comment by Devoe-97** [comment]
> May I ask how the npz file was generated？

use pickle.dump

**Comment by Bailin-He** [comment]
> > May I ask how the npz file was generated？
> 
> use pickle.dump

sorry，I would like to know how paid_info is generated in the npz file？look forward your reply

**Comment by Devoe-97** [comment]
> > > May I ask how the npz file was generated？
> > 
> > 
> > use pickle.dump
> 
> sorry，I would like to know how paid_info is generated in the npz file？look forward your reply

You could refer here:  https://github.com/mihaidusmanu/d2-net/blob/master/megadepth_utils/preprocess_scene.py

**Comment by Bailin-He** [comment]
> > > > May I ask how the npz file was generated？
> > > 
> > > 
> > > use pickle.dump
> > 
> > 
> > sorry，I would like to know how paid_info is generated in the npz file？look forward your reply
> 
> You could refer here: https://github.com/mihaidusmanu/d2-net/blob/master/megadepth_utils/preprocess_scene.py

It seems that there is no calculation related to `paid_info`

**Comment by Devoe-97** [comment]
> > > > > May I ask how the npz file was generated？
> > > > 
> > > > 
> > > > use pickle.dump
> > > 
> > > 
> > > sorry，I would like to know how paid_info is generated in the npz file？look forward your reply
> > 
> > 
> > You could refer here: https://github.com/mihaidusmanu/d2-net/blob/master/megadepth_utils/preprocess_scene.py
> 
> It seems that there is no calculation related to `paid_info`

what is 'paid_info' ?

**Comment by Bailin-He** [comment]
pair_infos

**Comment by Devoe-97** [comment]
> pair_infos

https://github.com/zju3dv/LoFTR/issues/85

**Comment by Bailin-He** [comment]
> > pair_infos
> 
> #85

Do you have the corresponding code？

**Comment by Bailin-He** [comment]
> > pair_infos
> 
> #85

Have you generated MegaDepth's indices yet？I searched for many days but couldn't find a way to solve it
